windowrule = float on, match:class clipse
windowrule = size 622 652, match:class clipse

# PiP для браузеров
windowrule = float on, match:class (firefox|floorp|helium), match:title ^Picture-in-Picture$

# TUI приложения в foot
windowrule = float on, match:title (bluetuith|nmtui|pulsemixer)
windowrule = float on, match:title btop
windowrule = size (monitor_w*0.7) (monitor_h*0.7), match:title btop
windowrule = center on, match:title btop

# Screenshare / portal диалоги
windowrule = float on, match:class xdg-desktop-portal
